import type { NextPage } from 'next'
import Head from 'next/head'
import { Home as HomePage } from '../page-components/home'
import {useEffect} from "react";

const Home: NextPage = () => {
    useEffect(() => {
        fetch('/api/articles').then(s => s.json()).then(r => {
            console.log(r);
        })
    }, []);
  return (
    <div >
      <Head>
        <title>Stanislav Panchenko</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main >
          <HomePage />
      </main>
    </div>
  )
}

export default Home
